"""Telegram Bot API provider for merchant alert delivery.

The bot token and chat ID are kept in the environment.  Open the bot and send
``/start`` once before testing: Telegram does not allow bots to begin a direct
message with a user on their own.
"""

from __future__ import annotations

import os
from typing import Any, Optional

import httpx

from .base import MessagingError, MessagingNotConfigured

API_ROOT = "https://api.telegram.org"
SEND_TIMEOUT = 20.0
POLL_TIMEOUT = 25.0
MAX_BODY_CHARS = 4096


def _clean(name: str) -> str:
    value = (os.environ.get(name) or "").strip()
    return "" if value.upper().startswith("YOUR_") else value


def bot_token() -> str:
    return _clean("TELEGRAM_BOT_TOKEN")


def recipient_default() -> str:
    return _clean("TELEGRAM_CHAT_ID")


def notifications_enabled() -> bool:
    value = os.environ.get("TELEGRAM_NOTIFICATIONS_ENABLED", "").strip().lower()
    return value in {"1", "true", "yes", "on"}


def has_credentials() -> bool:
    return bool(bot_token())


def is_configured() -> bool:
    return bool(has_credentials() and recipient_default())


def mask_chat_id(value: str) -> Optional[str]:
    if not value:
        return None
    if len(value) <= 4:
        return "*" * len(value)
    return "*" * (len(value) - 4) + value[-4:]


def status() -> dict:
    missing = [
        name for name, present in (
            ("TELEGRAM_BOT_TOKEN", bot_token()),
            ("TELEGRAM_CHAT_ID", recipient_default()),
        ) if not present
    ]
    return {
        "provider": "telegram",
        "configured": is_configured(),
        "credentials_present": has_credentials(),
        "enabled": notifications_enabled(),
        "channel": "telegram",
        "to": mask_chat_id(recipient_default()),
        "missing": missing,
        "note": "Telegram Bot API. Start the bot or add it to the target group before sending.",
    }


def _target(to: Optional[str]) -> str:
    target = (to or recipient_default()).strip()
    if not target:
        raise MessagingNotConfigured("No Telegram chat ID. Set TELEGRAM_CHAT_ID in .env.")
    return target


def _call_api(
    method: str,
    *,
    json: Optional[dict[str, Any]] = None,
    data: Optional[dict[str, Any]] = None,
    files: Optional[dict[str, Any]] = None,
    timeout: float = SEND_TIMEOUT,
) -> dict:
    """Call Telegram without ever including the bot token in an error."""
    try:
        response = httpx.post(
            f"{API_ROOT}/bot{bot_token()}/{method}",
            json=json,
            data=data,
            files=files,
            timeout=timeout,
        )
    except httpx.HTTPError as exc:
        raise MessagingError(f"Could not reach Telegram: {type(exc).__name__}") from exc

    try:
        payload = response.json()
    except ValueError as exc:
        raise MessagingError("Telegram returned a non-JSON response.") from exc

    if response.status_code >= 400 or not payload.get("ok"):
        description = payload.get("description") or f"HTTP {response.status_code}"
        raise MessagingError(f"Telegram rejected the request: {description}")
    return payload.get("result") or {}


def send(body: str, to: Optional[str] = None) -> dict:
    if not has_credentials():
        raise MessagingNotConfigured("Telegram is not configured. Need TELEGRAM_BOT_TOKEN in .env.")

    target = _target(to)

    text = body.strip()[:MAX_BODY_CHARS]
    message = _call_api(
        "sendMessage",
        json={"chat_id": target, "text": text, "disable_web_page_preview": True},
    )
    return {
        "sid": str(message.get("message_id") or ""),
        "status": "accepted",
        "channel": "telegram",
        "to": mask_chat_id(target),
        "body": text,
    }


def send_audio(
    audio: bytes,
    *,
    extension: str = "mp3",
    mime_type: str = "audio/mpeg",
    to: Optional[str] = None,
) -> dict:
    """Send a playable audio reply generated by a text-to-speech provider."""
    if not has_credentials():
        raise MessagingNotConfigured("Telegram is not configured. Need TELEGRAM_BOT_TOKEN in .env.")
    if not audio:
        raise MessagingError("Cannot send empty Telegram audio.")

    target = _target(to)
    message = _call_api(
        "sendAudio",
        data={"chat_id": target, "title": "Sujit Shopwala AI reply"},
        files={"audio": (f"reply.{extension}", audio, mime_type)},
        timeout=SEND_TIMEOUT + 30.0,
    )
    return {
        "sid": str(message.get("message_id") or ""),
        "status": "accepted",
        "channel": "telegram",
        "to": mask_chat_id(target),
        "audio": True,
    }


def get_updates(offset: Optional[int] = None, timeout: float = POLL_TIMEOUT) -> list[dict]:
    """Long-poll pending bot updates. This needs only the bot token."""
    if not has_credentials():
        raise MessagingNotConfigured("Telegram is not configured. Need TELEGRAM_BOT_TOKEN in .env.")

    wait = max(0, min(int(timeout), 50))
    payload: dict[str, Any] = {"timeout": wait, "allowed_updates": ["message"]}
    if offset is not None:
        payload["offset"] = offset
    updates = _call_api("getUpdates", json=payload, timeout=wait + 15.0)
    return updates if isinstance(updates, list) else []
