"""
Paytm merchant data provider.

An abstraction over where transaction data comes from, so the rest of the
product never assumes. Today there is exactly one working implementation and
it reads a generated CSV.

Stated plainly, because it matters: THIS PROJECT HAS NO PAYTM API ACCESS.
Nothing here calls Paytm. `transactions.csv` is synthetic data produced by
`data/generate_data.py`. The abstraction exists so a real integration can be
dropped in without touching the analytics, not to imply one exists.
"""

from __future__ import annotations

import os
from abc import ABC, abstractmethod
from typing import Optional

import pandas as pd

from . import data_loader


class PaytmMerchantDataProvider(ABC):
    """What the analytics layer needs from any source of merchant data."""

    name: str = "abstract"
    is_live: bool = False

    @abstractmethod
    def transactions(self) -> pd.DataFrame:
        """Successful transactions, with timestamp/amount/customer_id columns."""

    @abstractmethod
    def merchant_profile(self) -> dict:
        """Merchant identity and the as-of date the analysis anchors on."""

    def capabilities(self) -> dict:
        """
        What this source can and cannot answer.

        `line_item_detail` is the one that changes product behaviour: without
        it, transaction correlation can only ever be temporal.
        """
        return {
            "transaction_amounts": True,
            "transaction_timestamps": True,
            "customer_identifiers": True,
            "line_item_detail": False,
            "real_time": False,
            "campaign_activation": False,
        }

    def describe(self) -> dict:
        return {
            "provider": self.name,
            "is_live": self.is_live,
            "capabilities": self.capabilities(),
        }


class MockPaytmMerchantDataProvider(PaytmMerchantDataProvider):
    """
    The working implementation: a seeded, synthetic merchant.

    Deterministic by design. The same CSV always produces the same score,
    which is what makes the demo reproducible and the tests meaningful.
    """

    name = "mock-csv"
    is_live = False

    def transactions(self) -> pd.DataFrame:
        return data_loader.load_transactions()

    def merchant_profile(self) -> dict:
        return data_loader.load_meta()

    def capabilities(self) -> dict:
        caps = super().capabilities()
        caps["note"] = (
            "Synthetic data generated by data/generate_data.py. No Paytm API is "
            "contacted. Amounts and timestamps are realistic; there are no "
            "product line items, so a payment cannot be tied to a specific SKU."
        )
        return caps


class FuturePaytmAPIProvider(PaytmMerchantDataProvider):
    """
    Placeholder for a real Paytm for Business integration.

    Intentionally not implemented. It documents the seam and raises clearly if
    anyone selects it, rather than silently pretending to be live.
    """

    name = "paytm-api"
    is_live = True

    def _unavailable(self) -> None:
        raise NotImplementedError(
            "No Paytm API integration exists in this project. Merchant API "
            "access requires a registered Paytm for Business account and "
            "approved credentials. Set PAYTM_PROVIDER=mock to use the "
            "included synthetic dataset."
        )

    def transactions(self) -> pd.DataFrame:
        self._unavailable()
        raise AssertionError("unreachable")

    def merchant_profile(self) -> dict:
        self._unavailable()
        raise AssertionError("unreachable")

    def capabilities(self) -> dict:
        caps = super().capabilities()
        caps["line_item_detail"] = True
        caps["real_time"] = True
        caps["campaign_activation"] = True
        caps["note"] = "Not implemented. Documents the intended integration seam."
        return caps


_provider: Optional[PaytmMerchantDataProvider] = None


def get_provider() -> PaytmMerchantDataProvider:
    global _provider
    if _provider is None:
        choice = os.environ.get("PAYTM_PROVIDER", "mock").strip().lower()
        _provider = (
            FuturePaytmAPIProvider() if choice in {"api", "live", "paytm"}
            else MockPaytmMerchantDataProvider()
        )
    return _provider


def status() -> dict:
    provider = get_provider()
    return {
        **provider.describe(),
        "disclaimer": (
            "Transaction intelligence runs on a synthetic merchant dataset. "
            "This project does not connect to Paytm production systems."
        ),
    }
